-- Translate the inherited RuoYi menu / dictionary / config labels to English.

update sys_menu set menu_name = 'System' where menu_id = 1;
update sys_menu set menu_name = 'Monitoring' where menu_id = 2;
update sys_menu set menu_name = 'Tools' where menu_id = 3;
update sys_menu set menu_name = 'Users' where menu_id = 100;
update sys_menu set menu_name = 'Roles' where menu_id = 101;
update sys_menu set menu_name = 'Menus' where menu_id = 102;
update sys_menu set menu_name = 'Departments' where menu_id = 103;
update sys_menu set menu_name = 'Posts' where menu_id = 104;
update sys_menu set menu_name = 'Dictionaries' where menu_id = 105;
update sys_menu set menu_name = 'Config parameters' where menu_id = 106;
update sys_menu set menu_name = 'Notices' where menu_id = 107;
update sys_menu set menu_name = 'Logs' where menu_id = 108;
update sys_menu set menu_name = 'Online users' where menu_id = 109;
update sys_menu set menu_name = 'Scheduled jobs' where menu_id = 110;
update sys_menu set menu_name = 'Data monitor' where menu_id = 111;
update sys_menu set menu_name = 'Server monitor' where menu_id = 112;
update sys_menu set menu_name = 'Cache monitor' where menu_id = 113;
update sys_menu set menu_name = 'Cache list' where menu_id = 114;
update sys_menu set menu_name = 'Form builder' where menu_id = 115;
update sys_menu set menu_name = 'Code generator' where menu_id = 116;
update sys_menu set menu_name = 'API docs' where menu_id = 117;
update sys_menu set menu_name = 'Operation log' where menu_id = 500;
update sys_menu set menu_name = 'Login log' where menu_id = 501;
update sys_menu set menu_name = 'Query user' where menu_id = 1000;
update sys_menu set menu_name = 'Add user' where menu_id = 1001;
update sys_menu set menu_name = 'Edit user' where menu_id = 1002;
update sys_menu set menu_name = 'Delete user' where menu_id = 1003;
update sys_menu set menu_name = 'Export users' where menu_id = 1004;
update sys_menu set menu_name = 'Import users' where menu_id = 1005;
update sys_menu set menu_name = 'Reset password' where menu_id = 1006;
update sys_menu set menu_name = 'Query role' where menu_id = 1007;
update sys_menu set menu_name = 'Add role' where menu_id = 1008;
update sys_menu set menu_name = 'Edit role' where menu_id = 1009;
update sys_menu set menu_name = 'Delete role' where menu_id = 1010;
update sys_menu set menu_name = 'Export roles' where menu_id = 1011;
update sys_menu set menu_name = 'Query menu' where menu_id = 1012;
update sys_menu set menu_name = 'Add menu' where menu_id = 1013;
update sys_menu set menu_name = 'Edit menu' where menu_id = 1014;
update sys_menu set menu_name = 'Delete menu' where menu_id = 1015;
update sys_menu set menu_name = 'Query department' where menu_id = 1016;
update sys_menu set menu_name = 'Add department' where menu_id = 1017;
update sys_menu set menu_name = 'Edit department' where menu_id = 1018;
update sys_menu set menu_name = 'Delete department' where menu_id = 1019;
update sys_menu set menu_name = 'Query post' where menu_id = 1020;
update sys_menu set menu_name = 'Add post' where menu_id = 1021;
update sys_menu set menu_name = 'Edit post' where menu_id = 1022;
update sys_menu set menu_name = 'Delete post' where menu_id = 1023;
update sys_menu set menu_name = 'Export posts' where menu_id = 1024;
update sys_menu set menu_name = 'Query dictionary' where menu_id = 1025;
update sys_menu set menu_name = 'Add dictionary' where menu_id = 1026;
update sys_menu set menu_name = 'Edit dictionary' where menu_id = 1027;
update sys_menu set menu_name = 'Delete dictionary' where menu_id = 1028;
update sys_menu set menu_name = 'Export dictionaries' where menu_id = 1029;
update sys_menu set menu_name = 'Query parameter' where menu_id = 1030;
update sys_menu set menu_name = 'Add parameter' where menu_id = 1031;
update sys_menu set menu_name = 'Edit parameter' where menu_id = 1032;
update sys_menu set menu_name = 'Delete parameter' where menu_id = 1033;
update sys_menu set menu_name = 'Export parameters' where menu_id = 1034;
update sys_menu set menu_name = 'Query notice' where menu_id = 1035;
update sys_menu set menu_name = 'Add notice' where menu_id = 1036;
update sys_menu set menu_name = 'Edit notice' where menu_id = 1037;
update sys_menu set menu_name = 'Delete notice' where menu_id = 1038;
update sys_menu set menu_name = 'Query operation log' where menu_id = 1039;
update sys_menu set menu_name = 'Delete operation log' where menu_id = 1040;
update sys_menu set menu_name = 'Export operation log' where menu_id = 1041;
update sys_menu set menu_name = 'Query login log' where menu_id = 1042;
update sys_menu set menu_name = 'Delete login log' where menu_id = 1043;
update sys_menu set menu_name = 'Export login log' where menu_id = 1044;
update sys_menu set menu_name = 'Account unlock' where menu_id = 1045;
update sys_menu set menu_name = 'Query online users' where menu_id = 1046;
update sys_menu set menu_name = 'Bulk force logout' where menu_id = 1047;
update sys_menu set menu_name = 'Force logout' where menu_id = 1048;
update sys_menu set menu_name = 'Query job' where menu_id = 1049;
update sys_menu set menu_name = 'Add job' where menu_id = 1050;
update sys_menu set menu_name = 'Edit job' where menu_id = 1051;
update sys_menu set menu_name = 'Delete job' where menu_id = 1052;
update sys_menu set menu_name = 'Change job status' where menu_id = 1053;
update sys_menu set menu_name = 'Export jobs' where menu_id = 1054;
update sys_menu set menu_name = 'Query generation' where menu_id = 1055;
update sys_menu set menu_name = 'Edit generation' where menu_id = 1056;
update sys_menu set menu_name = 'Delete generation' where menu_id = 1057;
update sys_menu set menu_name = 'Import code' where menu_id = 1058;
update sys_menu set menu_name = 'Preview code' where menu_id = 1059;
update sys_menu set menu_name = 'Generate code' where menu_id = 1060;

-- the RuoYi marketing link is not part of the Nadoumi admin
update sys_menu set visible = '1', status = '1' where menu_id = 4;

update sys_dict_type set dict_name = 'User gender' where dict_type = 'sys_user_sex';
update sys_dict_type set dict_name = 'Show / hide' where dict_type = 'sys_show_hide';
update sys_dict_type set dict_name = 'Enabled / disabled' where dict_type = 'sys_normal_disable';
update sys_dict_type set dict_name = 'Job status' where dict_type = 'sys_job_status';
update sys_dict_type set dict_name = 'Job group' where dict_type = 'sys_job_group';
update sys_dict_type set dict_name = 'Yes / no' where dict_type = 'sys_yes_no';
update sys_dict_type set dict_name = 'Notice type' where dict_type = 'sys_notice_type';
update sys_dict_type set dict_name = 'Notice status' where dict_type = 'sys_notice_status';
update sys_dict_type set dict_name = 'Operation type' where dict_type = 'sys_oper_type';
update sys_dict_type set dict_name = 'Result status' where dict_type = 'sys_common_status';

update sys_dict_data set dict_label = 'Success' where dict_type = 'sys_common_status' and dict_value = '0';
update sys_dict_data set dict_label = 'Failure' where dict_type = 'sys_common_status' and dict_value = '1';
update sys_dict_data set dict_label = 'Default' where dict_type = 'sys_job_group' and dict_value = 'DEFAULT';
update sys_dict_data set dict_label = 'System' where dict_type = 'sys_job_group' and dict_value = 'SYSTEM';
update sys_dict_data set dict_label = 'Normal' where dict_type = 'sys_job_status' and dict_value = '0';
update sys_dict_data set dict_label = 'Paused' where dict_type = 'sys_job_status' and dict_value = '1';
update sys_dict_data set dict_label = 'Enabled' where dict_type = 'sys_normal_disable' and dict_value = '0';
update sys_dict_data set dict_label = 'Disabled' where dict_type = 'sys_normal_disable' and dict_value = '1';
update sys_dict_data set dict_label = 'Open' where dict_type = 'sys_notice_status' and dict_value = '0';
update sys_dict_data set dict_label = 'Closed' where dict_type = 'sys_notice_status' and dict_value = '1';
update sys_dict_data set dict_label = 'Notification' where dict_type = 'sys_notice_type' and dict_value = '1';
update sys_dict_data set dict_label = 'Announcement' where dict_type = 'sys_notice_type' and dict_value = '2';
update sys_dict_data set dict_label = 'Insert' where dict_type = 'sys_oper_type' and dict_value = '1';
update sys_dict_data set dict_label = 'Update' where dict_type = 'sys_oper_type' and dict_value = '2';
update sys_dict_data set dict_label = 'Delete' where dict_type = 'sys_oper_type' and dict_value = '3';
update sys_dict_data set dict_label = 'Grant' where dict_type = 'sys_oper_type' and dict_value = '4';
update sys_dict_data set dict_label = 'Export' where dict_type = 'sys_oper_type' and dict_value = '5';
update sys_dict_data set dict_label = 'Import' where dict_type = 'sys_oper_type' and dict_value = '6';
update sys_dict_data set dict_label = 'Force logout' where dict_type = 'sys_oper_type' and dict_value = '7';
update sys_dict_data set dict_label = 'Generate code' where dict_type = 'sys_oper_type' and dict_value = '8';
update sys_dict_data set dict_label = 'Clean data' where dict_type = 'sys_oper_type' and dict_value = '9';
update sys_dict_data set dict_label = 'Other' where dict_type = 'sys_oper_type' and dict_value = '0';
update sys_dict_data set dict_label = 'Show' where dict_type = 'sys_show_hide' and dict_value = '0';
update sys_dict_data set dict_label = 'Hide' where dict_type = 'sys_show_hide' and dict_value = '1';
update sys_dict_data set dict_label = 'Male' where dict_type = 'sys_user_sex' and dict_value = '0';
update sys_dict_data set dict_label = 'Female' where dict_type = 'sys_user_sex' and dict_value = '1';
update sys_dict_data set dict_label = 'Unknown' where dict_type = 'sys_user_sex' and dict_value = '2';
update sys_dict_data set dict_label = 'Yes' where dict_type = 'sys_yes_no' and dict_value = 'Y';
update sys_dict_data set dict_label = 'No' where dict_type = 'sys_yes_no' and dict_value = 'N';

update sys_config set config_name = 'Layout: default skin' where config_key = 'sys.index.skinName';
update sys_config set config_name = 'Users: initial password' where config_key = 'sys.user.initPassword';
update sys_config set config_name = 'Layout: sidebar theme' where config_key = 'sys.index.sideTheme';
update sys_config set config_name = 'Self-service: captcha enabled' where config_key = 'sys.account.captchaEnabled';
update sys_config set config_name = 'Self-service: user registration enabled' where config_key = 'sys.account.registerUser';
update sys_config set config_name = 'Login: IP blacklist' where config_key = 'sys.login.blackIPList';
update sys_config set config_name = 'Users: initial-password change policy' where config_key = 'sys.account.initPasswordModify';
update sys_config set config_name = 'Users: password expiry (days)' where config_key = 'sys.account.passwordValidateDays';
update sys_config set config_name = 'Users: password character set' where config_key = 'sys.account.chrtype';
