/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTabs: typeof import('./src/components/ui/AppTabs.vue')['default']
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    ComingSoonCard: typeof import('./src/components/dashboard/ComingSoonCard.vue')['default']
    DashboardGroup: typeof import('./src/components/dashboard/DashboardGroup.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    DescriptionList: typeof import('./src/components/ui/DescriptionList.vue')['default']
    DonutChart: typeof import('./src/components/dashboard/DonutChart.vue')['default']
    DonutChartSkeleton: typeof import('./src/components/dashboard/DonutChartSkeleton.vue')['default']
    DonutStat: typeof import('./src/components/dashboard/DonutStat.vue')['default']
    Drawer: typeof import('./src/components/ui/Drawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ui/ErrorState.vue')['default']
    FilterBar: typeof import('./src/components/ui/FilterBar.vue')['default']
    FormSection: typeof import('./src/components/ui/FormSection.vue')['default']
    ImageUpload: typeof import('./src/components/ui/ImageUpload.vue')['default']
    LoadingState: typeof import('./src/components/ui/LoadingState.vue')['default']
    MoneyField: typeof import('./src/components/ui/MoneyField.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/ui/SearchInput.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    StatePanel: typeof import('./src/components/ui/StatePanel.vue')['default']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
  }
}
