/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTabs: typeof import('./src/components/ui/AppTabs.vue')['default']
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    ComingSoonCard: typeof import('./src/components/dashboard/ComingSoonCard.vue')['default']
    DashboardGroup: typeof import('./src/components/dashboard/DashboardGroup.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    DescriptionList: typeof import('./src/components/ui/DescriptionList.vue')['default']
    DonutStat: typeof import('./src/components/dashboard/DonutStat.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ui/ErrorState.vue')['default']
    FilterBar: typeof import('./src/components/ui/FilterBar.vue')['default']
    LoadingState: typeof import('./src/components/ui/LoadingState.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RecentApplicants: typeof import('./src/components/dashboard/RecentApplicants.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/ui/SearchInput.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
