package com.nadoumi.finance.service;

import com.nadoumi.finance.domain.Expense;
import java.time.format.DateTimeFormatter;
import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

/**
 * Renders a printable, self-contained HTML receipt for an approved/paid
 * {@link Expense}. No external dependency — the browser's "Print → Save as PDF"
 * produces the PDF; the page auto-opens the print dialog.
 */
@Component
public class ReceiptWriter {

    private static final DateTimeFormatter D = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    public String renderHtml(Expense e) {
        String receiptNo = e.getReceiptNo() == null ? "(pending approval)" : e.getReceiptNo();
        StringBuilder rows = new StringBuilder();
        row(rows, "Receipt no.", receiptNo);
        row(rows, "Status", e.getStatus());
        row(rows, "Date of expense", e.getSpentOn() == null ? "—" : e.getSpentOn().format(D));
        row(rows, "Category", e.getCategoryName());
        row(rows, "Vendor", e.getVendor());
        row(rows, "Payment method", e.getPaymentMethod());
        row(rows, "Description", e.getTitle()
                + (e.getDescription() == null ? "" : " — " + e.getDescription()));
        row(rows, "Submitted by", e.getSubmittedByName());
        row(rows, "Approved by", (e.getApprovedByName() == null ? "—" : e.getApprovedByName())
                + (e.getApprovedAt() == null ? "" : " on " + e.getApprovedAt().toLocalDate().format(D)));

        String amount = (e.getCurrency() == null ? "" : e.getCurrency() + " ") + String.valueOf(e.getAmount());

        return """
            <!doctype html><html><head><meta charset="utf-8">
            <title>Expense receipt %s</title>
            <style>
              body{font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;margin:0;padding:40px;}
              .sheet{max-width:640px;margin:0 auto;}
              h1{font-size:22px;margin:0 0 2px;}
              .org{color:#475569;margin:0 0 24px;}
              table{width:100%%;border-collapse:collapse;margin-bottom:20px;}
              th,td{border:1px solid #e2e8f0;padding:8px 10px;text-align:left;vertical-align:top;}
              th{width:34%%;background:#f8fafc;font-weight:600;}
              .total{display:flex;justify-content:flex-end;gap:24px;font-size:18px;font-weight:700;}
              .foot{margin-top:44px;color:#94a3b8;font-size:11px;}
              @media print{body{padding:0;} .noprint{display:none;}}
            </style></head><body><div class="sheet">
              <button class="noprint" onclick="window.print()" style="float:right">Print / Save as PDF</button>
              <h1>Expense Receipt</h1>
              <p class="org">Nadoumi — International Education Platform</p>
              <table>%s</table>
              <div class="total"><span>TOTAL</span><span>%s</span></div>
              <p class="foot">Generated by the Nadoumi admin console. Record of an approved internal expense.</p>
            </div>
            <script>window.addEventListener('load',function(){setTimeout(function(){window.print()},300)})</script>
            </body></html>
            """.formatted(esc(receiptNo), rows, esc(amount));
    }

    private static void row(StringBuilder sb, String label, String value) {
        sb.append("<tr><th>").append(esc(label)).append("</th><td>")
                .append(value == null || value.isBlank() ? "—" : esc(value)).append("</td></tr>");
    }

    private static String esc(String s) {
        return s == null ? "" : HtmlUtils.htmlEscape(s);
    }
}
